export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_MISSING = 'TOKEN_MISSING',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Registration
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',

  // Authorization
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',

  // Project authorization
  PROJECT_ACTOR_REQUIRED = 'PROJECT_ACTOR_REQUIRED',
  PROJECT_ACTOR_NOT_FOUND = 'PROJECT_ACTOR_NOT_FOUND',
  PROJECT_ACTOR_INACTIVE = 'PROJECT_ACTOR_INACTIVE',
  PROJECT_ACCESS_DENIED = 'PROJECT_ACCESS_DENIED',
  PROJECT_CREATION_FORBIDDEN = 'PROJECT_CREATION_FORBIDDEN',
  PROJECT_MANAGER_ASSIGNMENT_FORBIDDEN = 'PROJECT_MANAGER_ASSIGNMENT_FORBIDDEN',
  PROJECT_DELETION_FORBIDDEN = 'PROJECT_DELETION_FORBIDDEN',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_MANAGER_NOT_FOUND = 'PROJECT_MANAGER_NOT_FOUND',
  PROJECT_MANAGER_INACTIVE = 'PROJECT_MANAGER_INACTIVE',
  INVALID_PROJECT_MANAGER_ROLE = 'INVALID_PROJECT_MANAGER_ROLE',
  INVALID_PROJECT_STATUS_TRANSITION = 'INVALID_PROJECT_STATUS_TRANSITION',
  INVALID_PROJECT_DATE_RANGE = 'INVALID_PROJECT_DATE_RANGE',
  PROJECT_ACTIVATION_REQUIREMENTS_NOT_MET = 'PROJECT_ACTIVATION_REQUIREMENTS_NOT_MET',
  PROJECT_COMPLETION_REQUIREMENTS_NOT_MET = 'PROJECT_COMPLETION_REQUIREMENTS_NOT_MET',
  PROJECT_DELETION_NOT_ALLOWED = 'PROJECT_DELETION_NOT_ALLOWED',

  // Project Milestone
  MILESTONE_NOT_FOUND = 'MILESTONE_NOT_FOUND',
  MILESTONE_TOTAL_WEIGHT_EXCEEDED = 'MILESTONE_TOTAL_WEIGHT_EXCEEDED',
  MILESTONE_INVALID_STATUS_PROGRESS = 'MILESTONE_INVALID_STATUS_PROGRESS',
  MILESTONE_MODIFICATION_NOT_ALLOWED = 'MILESTONE_MODIFICATION_NOT_ALLOWED',
  MILESTONE_IN_USE = 'MILESTONE_IN_USE',
  MILESTONE_CONCURRENCY_CONFLICT = 'MILESTONE_CONCURRENCY_CONFLICT',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Generic
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Google Calendar
  CALENDAR_USER_REQUIRED = 'CALENDAR_USER_REQUIRED',
  CALENDAR_NOT_CONNECTED = 'CALENDAR_NOT_CONNECTED',
  CALENDAR_INVALID_STATE = 'CALENDAR_INVALID_STATE',
  CALENDAR_AUTHORIZATION_DENIED = 'CALENDAR_AUTHORIZATION_DENIED',
  CALENDAR_AUTHORIZATION_FAILED = 'CALENDAR_AUTHORIZATION_FAILED',
  CALENDAR_REFRESH_TOKEN_MISSING = 'CALENDAR_REFRESH_TOKEN_MISSING',
  CALENDAR_REAUTH_REQUIRED = 'CALENDAR_REAUTH_REQUIRED',
  CALENDAR_PERMISSION_DENIED = 'CALENDAR_PERMISSION_DENIED',
  CALENDAR_EVENT_NOT_FOUND = 'CALENDAR_EVENT_NOT_FOUND',
  CALENDAR_INVALID_DATE_RANGE = 'CALENDAR_INVALID_DATE_RANGE',
  CALENDAR_SERVICE_UNAVAILABLE = 'CALENDAR_SERVICE_UNAVAILABLE',
  CALENDAR_GOOGLE_API_ERROR = 'CALENDAR_GOOGLE_API_ERROR',
}
