export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_MISSING = 'TOKEN_MISSING',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Registration
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',

  // Authorization
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',

  // Project authorization
  PROJECT_ACTOR_REQUIRED = 'PROJECT_ACTOR_REQUIRED',
  PROJECT_ACTOR_NOT_FOUND = 'PROJECT_ACTOR_NOT_FOUND',
  PROJECT_ACTOR_INACTIVE = 'PROJECT_ACTOR_INACTIVE',
  PROJECT_ACCESS_DENIED = 'PROJECT_ACCESS_DENIED',
  PROJECT_CREATION_FORBIDDEN = 'PROJECT_CREATION_FORBIDDEN',
  PROJECT_MANAGER_ASSIGNMENT_FORBIDDEN = 'PROJECT_MANAGER_ASSIGNMENT_FORBIDDEN',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_MANAGER_NOT_FOUND = 'PROJECT_MANAGER_NOT_FOUND',
  PROJECT_MANAGER_INACTIVE = 'PROJECT_MANAGER_INACTIVE',
  INVALID_PROJECT_MANAGER_ROLE = 'INVALID_PROJECT_MANAGER_ROLE',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Generic
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
