name: Backend CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  backend-ci:
    uses: ConstructPro-ERP/infra/.github/workflows/backend-ci.yml@v1
    secrets: inherit
