name: Backend CI

on:
  push:
    branches:
      - develop
      - main
      - "feature/**"
      - "fix/**"

  pull_request:
    branches:
      - develop
      - main

jobs:
  backend-ci:
    uses: ConstructPro-ERP/infra/.github/workflows/backend-ci.yml@v1
    secrets: inherit
